http:
  port: ":8081"
  readTimeout: 4s
  writeTimeout: 4s

postgres:
  pg_user: "postgres"
  pg_database: "postgres"
  pg_host: "localhost"
  pg_port: "5436"
  pg_sslmode: "disable"
  pg_password: "qwerty"